### ISSUE TITLE
Fails on server

### ISSUE THREAD

**Issue by tomkiss** [smikhalevski/react-scroll-box#5]
With react running on both server and client, the component fails to run because 

```
ReferenceError: window is not defined
```

...is reported server side.

I'm relatively new to react but I'm having trouble getting past this issue. Is this use case something that you've tested against?

**Comment by smikhalevski** [comment]
Hello @tomkiss, you need to provide value for `nativeScroll` prop explicitly to render scroll box on server side.

**Comment by tomkiss** [comment]
I get the error when loading the component, e.g:

```
var ScrollBox = require('react-scroll-box');
```

Or

```
var ScrollBox = require('react-scroll-box').ScrollBox;
```

(Also: Hello, and thank-you!)

**Comment by smikhalevski** [comment]
@tomkiss `npm update` to react-scroll-box@**0.2.3** it includes a hotfix

**Comment by tomkiss** [comment]
Wow, thank you. 

I think you're the fastest responder I've ever seen on Github! 👍 

🚗 💨

**Comment by smikhalevski** [comment]
You are welcome) Please let me know if it turns out there any other issues with server-based rendering.

**Comment by tomkiss** [comment]
It seems to be running without any JS errors, I do see a warning:

```
Warning: This browser doesn't support the `onScroll` event
```

Not seeing any CSS styles being applied, just looking at that now.

**Comment by smikhalevski** [comment]
You need to import `react-scroll-box/target/out/index.css` on your page to have styles.

You can also customize and assemble them with [`react-scroll-box/src/main/scroll-box.less`](https://github.com/smikhalevski/react-scroll-box/blob/master/src/main/scroll-box.less) and then import.

**Update** About the warning, have a look at https://github.com/facebook/react/issues/631

**Comment by tomkiss** [comment]
Thanks! :)

**Comment by tomkiss** [comment]
Just reporting back on another warning. I'm getting the "_React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting..._"  in the browser.

Apart from that it's working beautifully.

**Comment by smikhalevski** [comment]
Markup created by scroll box componont is pretty constant with except for style class names. I never stumbled on such issue. What version of React are you using? What content are you rendering? 

What I can propose in order to find the reason of this issue:
1. Try to render your app on the client side and find a diff between server rendered markup and one created on the client.
1.5. Try to render with and without scroll box to ensure this component is the bottle neck.
2. Provide `nativeScroll` param explicitly, because it is the only place in code that relies on `window` object that exists on the client only.

Please keep me updated)

**Comment by tomkiss** [comment]
Gah, sorry - my bad. I'd absentmindedly disabled the nativeScroll.

**Comment by smikhalevski** [comment]
@tomkiss, did setting `nativeScroll={false}` solve the issue?

**Comment by mm-tom** [comment]
Yes, all good now - thanks!
