### ISSUE TITLE
ClassName issue

### ISSUE THREAD

**Issue by tomkiss** [smikhalevski/react-scroll-box#6]
Heya,

I think I've doung a bug - If I supply a ClassName attribute, it overrides the default value of .scroll-box--wrapped

This means that the track bars remain invisible, as they default to display: none are are overwritten by the CSS class which replies on .scroll-box--wrapped as an ancestor.

Manually adding in the class fixes the issue and the scrollbars become visible and interactive.

:)

**Comment by smikhalevski** [comment]
What you described is expected behavior.

**Short Answer** You need to specify `.scroll-box--wrapped` along with custom `className`

**Long Answer**
Scroll box may be in two states: _wrapped_ (it has scrollbars and crops its content) and _unwrapped_ (behaves like a plain `div`). The unwrapped mode is useful on mobile devices when you want user to scroll content along with page. These modes are toggled with `.scroll-box--wrapped` style class.

There is also a LESS mixin [`.scroll-box-wrap()`](https://github.com/smikhalevski/react-scroll-box/blob/master/src/main/scroll-box.less#L165) which can help you toggle wrapped-unwrapped modes depending on media queries.

For example, set `className={null}` for scroll box and use this snippet in your LESS styles to have unwrapped scroll box on displays smaller than 500px.

``` less
@media(min-width: 500px) {
  .scroll-box {
    .scroll-box-wrap();
  }
}
```

**Comment by tomkiss** [comment]
Perfect, thanks for the explanation.
