### ISSUE TITLE
Differences between wheelStep with wheel mouse and trackpad gesture

### ISSUE THREAD

**Issue by mario-lemes** [smikhalevski/react-scroll-box#7]
Hey @smikhalevski,

Nice to contact to you again. I saw there are some good changes here, congratz!

Let's go directly to the issue that cames to me here. I have noticed there are quite differences on the sensibility of the scrool when you scroll up or down with a wheel mouse or with a trackpad gesture on mac specifically. The last one is super fast, to fix it I need to change "wheelStepY" to 5px but as you know that value is too low for the rest of scenarios ( I use 40px as normal ). 

Do yo know any solution for this issue? I mean, to avoid the super fast scrolling with trackpad gesture on mac with 40px as wheelStepY.

Thank you very much!

**Comment by smikhalevski** [comment]
Hello @Yonirt,

I've made some investigations on MBP with trackpad and it turned out that `onMouseWheel` event is triggered way too frequent on this platform comparing to regular mouse wheel. I suppose that [`debounce`](https://lodash.com/docs#debounce) must be added to fix this issue. I'll create a fix for this problem and return back to you ASAP.

Thank you for finding such an issue!

**Comment by smikhalevski** [comment]
@Yonirt, have a look at **v0.2.4**. I've tested with FF, Safari and Chrome in OS X and thackpad seems to work well now.

**Comment by mario-lemes** [comment]
Great! I will take a look.

Thank you so much!
